/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminSeccionesRouteImport } from './routes/admin.secciones'
import { Route as CartaIndexRouteImport } from './routes/carta.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CartaSectionSlugIndexRouteImport } from './routes/carta.$sectionSlug.index'
import { Route as CartaSectionSlugProductSlugIndexRouteImport } from './routes/carta.$sectionSlug.$productSlug.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeccionesRoute = AdminSeccionesRouteImport.update({
  id: '/secciones',
  path: '/secciones',
  getParentRoute: () => AdminRoute,
} as any)
const CartaIndexRoute = CartaIndexRouteImport.update({
  id: '/carta/',
  path: '/carta/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaSectionSlugIndexRoute = CartaSectionSlugIndexRouteImport.update({
  id: '/carta/$sectionSlug/',
  path: '/carta/$sectionSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaSectionSlugProductSlugIndexRoute =
  CartaSectionSlugProductSlugIndexRouteImport.update({
    id: '/carta/$sectionSlug/$productSlug/',
    path: '/carta/$sectionSlug/$productSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/secciones': typeof AdminSeccionesRoute
  '/admin/': typeof AdminIndexRoute
  '/carta/': typeof CartaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/carta/$sectionSlug/': typeof CartaSectionSlugIndexRoute
  '/carta/$sectionSlug/$productSlug/': typeof CartaSectionSlugProductSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/secciones': typeof AdminSeccionesRoute
  '/admin': typeof AdminIndexRoute
  '/carta': typeof CartaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/carta/$sectionSlug': typeof CartaSectionSlugIndexRoute
  '/carta/$sectionSlug/$productSlug': typeof CartaSectionSlugProductSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/secciones': typeof AdminSeccionesRoute
  '/admin/': typeof AdminIndexRoute
  '/carta/': typeof CartaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/carta/$sectionSlug/': typeof CartaSectionSlugIndexRoute
  '/carta/$sectionSlug/$productSlug/': typeof CartaSectionSlugProductSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/categorias'
    | '/admin/secciones'
    | '/admin/'
    | '/carta/'
    | '/api/auth/$'
    | '/carta/$sectionSlug/'
    | '/carta/$sectionSlug/$productSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/admin/categorias'
    | '/admin/secciones'
    | '/admin'
    | '/carta'
    | '/api/auth/$'
    | '/carta/$sectionSlug'
    | '/carta/$sectionSlug/$productSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/categorias'
    | '/admin/secciones'
    | '/admin/'
    | '/carta/'
    | '/api/auth/$'
    | '/carta/$sectionSlug/'
    | '/carta/$sectionSlug/$productSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CartaIndexRoute: typeof CartaIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CartaSectionSlugIndexRoute: typeof CartaSectionSlugIndexRoute
  CartaSectionSlugProductSlugIndexRoute: typeof CartaSectionSlugProductSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/secciones': {
      id: '/admin/secciones'
      path: '/secciones'
      fullPath: '/admin/secciones'
      preLoaderRoute: typeof AdminSeccionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/carta/': {
      id: '/carta/'
      path: '/carta'
      fullPath: '/carta/'
      preLoaderRoute: typeof CartaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta/$sectionSlug/': {
      id: '/carta/$sectionSlug/'
      path: '/carta/$sectionSlug'
      fullPath: '/carta/$sectionSlug/'
      preLoaderRoute: typeof CartaSectionSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta/$sectionSlug/$productSlug/': {
      id: '/carta/$sectionSlug/$productSlug/'
      path: '/carta/$sectionSlug/$productSlug'
      fullPath: '/carta/$sectionSlug/$productSlug/'
      preLoaderRoute: typeof CartaSectionSlugProductSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminSeccionesRoute: typeof AdminSeccionesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminSeccionesRoute: AdminSeccionesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CartaIndexRoute: CartaIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CartaSectionSlugIndexRoute: CartaSectionSlugIndexRoute,
  CartaSectionSlugProductSlugIndexRoute: CartaSectionSlugProductSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
